export const inventoryModalStyles = {
  body: 'space-y-4',
  empty: 'py-6 text-center text-sm text-gray-500',
  list: 'space-y-3',
  row: 'space-y-2 rounded-xl border border-gray-200 p-3',
  rowHeader: 'flex items-center justify-between gap-2',
  titleWrap: 'flex min-w-0 flex-col',
  title: 'truncate text-sm font-semibold text-gray-900',
  meta: 'flex flex-wrap items-center gap-1.5',
  badge: 'inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium',
  badgeDay: 'bg-amber-100 text-amber-700',
  badgeNight: 'bg-indigo-100 text-indigo-700',
  badgeExpired: 'bg-red-100 text-red-700',
  badgeOk: 'bg-green-100 text-green-700',
  chip: 'inline-flex items-center rounded-md bg-gray-100 px-2 py-0.5 text-[11px] font-medium text-gray-600',
  volume: 'text-xs text-gray-500',
  pumpTimes: 'text-xs text-gray-500',
  pumpLabel: 'font-medium text-gray-600',
  locationLabel: 'text-xs font-medium text-gray-600',
  totalRow: 'flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2',
  totalLabel: 'text-sm text-gray-500',
  totalValue: 'text-sm font-semibold text-gray-900',
} as const;
